# Generated by Django 6.0.8 on 2026-09-09 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0002_alter_order_status_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='', max_length=255, verbose_name='Payment Provider')),
                ('currency', models.CharField(choices=[('qat. riyal', 'Qat. Riyal'), ('US. dollar', 'US Dollar'), ('tenge', 'Tenge')], default='qat. riyal', max_length=25, verbose_name='Payment Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=25, verbose_name='Payment Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='offers.order', verbose_name='order')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='', max_length=255, verbose_name='Payout Provider')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('on_hold', 'On Hold'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=25, verbose_name='Payout Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='offers.order', verbose_name='order')),
            ],
        ),
    ]
