# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('QAR', 'Qatari Riyal'), ('USD', 'US Dollar'), ('KZT', 'Tenge')], default='QAR', max_length=25, verbose_name='Payment Currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(max_length=255, verbose_name='Payment Provider'),
        ),
        migrations.AddField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payout Amount'),
        ),
        migrations.AddField(
            model_name='payout',
            name='currency',
            field=models.CharField(choices=[('QAR', 'Qatari Riyal'), ('USD', 'US Dollar'), ('KZT', 'Tenge')], default='QAR', max_length=25, verbose_name='Payout Currency'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='provider',
            field=models.CharField(max_length=255, verbose_name='Payout Provider'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=~models.Q(('provider', '')), name='payment_provider_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=~models.Q(('provider', '')), name='payout_provider_not_blank'),
        ),
    ]
