# Generated by Django 6.0.8 on 2026-09-08 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_request_status_alter_request_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default=0, max_length=20, verbose_name='Offering Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=25, verbose_name='Offer status')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='users.providerprofile', verbose_name='provider')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='users.request', verbose_name='request')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255, verbose_name='Message Body')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='offers.offer', verbose_name='offer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('funded', 'Funded'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('appeal', 'Appeal'), ('dispute', 'Dispute'), ('unresolved', 'Unresolved'), ('reverted', 'Reverted')], default='funded', max_length=25)),
                ('funded_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='offers.offer', verbose_name='offer')),
            ],
        ),
    ]
