# Generated by Django 6.0.8 on 2026-09-09 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('funded', 'Funded'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('appeal', 'Appeal'), ('dispute', 'Dispute'), ('unresolved', 'Unresolved'), ('reverted', 'Reverted')], default='funded', max_length=25, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(blank=True, max_length=255, verbose_name='Attached file hash')),
                ('storage_key', models.CharField(blank=True, max_length=255, verbose_name='Attached file key')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='offers.order', verbose_name='order')),
            ],
        ),
    ]
