# Generated by Django 6.0.8

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_order_status_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Offering Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='offers.offer', verbose_name='offer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('request', 'provider'), name='unique_active_offer_per_provider_per_request'),
        ),
    ]
