# Generated by Django 6.0.8 on 2026-09-16 05:16

from decimal import Decimal

import django.core.validators
from django.db import migrations
from django.db import models


def normalize_existing_offers(apps, schema_editor):
    offer = apps.get_model("offers", "Offer")
    offer.objects.filter(price__lte=0).update(price=Decimal("0.01"))
    request_ids = (
        offer.objects.filter(status="accepted")
        .values_list("request_id", flat=True)
        .distinct()
    )
    for request_id in request_ids:
        accepted_ids = offer.objects.filter(
            request_id=request_id,
            status="accepted",
        ).order_by("pk").values_list("pk", flat=True)
        offer.objects.filter(pk__in=accepted_ids[1:]).update(status="rejected")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("offers", "0005_move_request_to_requests_app"),
        ("requests", "0003_request_budget_non_negative"),
        ("users", "0006_move_request_to_requests_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Offer Comment"),
        ),
        migrations.AddField(
            model_name="offer",
            name="delivery_days",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Delivery days",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="offer",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Offer Price",
            ),
        ),
        migrations.RunPython(
            normalize_existing_offers,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["accepted"])),
                fields=("request",),
                name="unique_accepted_offer_per_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)),
                name="offer_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(
                condition=models.Q(("delivery_days__gt", 0)),
                name="offer_delivery_days_positive",
            ),
        ),
    ]
