# Generated by Django 6.0.8 on 2026-09-17 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_move_request_to_requests_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_time']},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['offer', 'date_time'], name='offers_message_offer_idx'),
        ),
    ]
