# Generated by Django 6.0.8 on 2026-09-16 05:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_move_request_to_requests_app'),
        ('requests', '0003_request_budget_non_negative'),
        ('users', '0006_move_request_to_requests_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Offer Comment'),
        ),
        migrations.AddField(
            model_name='offer',
            name='delivery_days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Delivery days'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Offer Price'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['accepted'])), fields=('request',), name='unique_accepted_offer_per_request'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='offer_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_days__gt', 0)), name='offer_delivery_days_positive'),
        ),
    ]
