# Generated by Django 6.0.8

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0005_move_request_to_requests_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("funded", "Funded"),
                    ("sent", "Sent"),
                    ("revision_requested", "Revision requested"),
                    ("confirmed", "Confirmed"),
                    ("appeal", "Appeal"),
                    ("dispute", "Dispute"),
                    ("unresolved", "Unresolved"),
                    ("reverted", "Reverted"),
                ],
                default="funded",
                max_length=25,
                verbose_name="status",
            ),
        ),
    ]
