# Generated by Django 6.0.8 on 2026-09-09 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Dipute reason')),
                ('resolution', models.CharField(max_length=255, verbose_name='Dispute resolution')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='offers.order', verbose_name='order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Review Rating')),
                ('body', models.CharField(blank=True, max_length=255, verbose_name='Review Body')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='offers.order', verbose_name='order')),
            ],
        ),
    ]
