# Generated by Django 6.0.8 on 2026-09-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(default='', max_length=255, verbose_name='Dipute reason'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='resolution',
            field=models.CharField(default='', max_length=255, verbose_name='Dispute resolution'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Review Rating'),
        ),
    ]
