# Generated by Django 6.0.8 on 2026-09-08 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_user_uuid(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all().iterator():
        user.uuid = uuid.uuid4()
        user.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='User location'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, unique=False),
        ),
        migrations.RunPython(backfill_user_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20, verbose_name='KYC status')),
                ('payout_provider', models.CharField(blank=True, max_length=225, verbose_name='Payout provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('document', 'Document'), ('course', 'Course'), ('book', 'Book'), ('journal', 'Journal'), ('article', 'Article'), ('other', 'Other')], default='other', max_length=255, verbose_name='Request Category')),
                ('budget', models.CharField(blank=True, max_length=255, null=True, verbose_name='RequestBudget')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_customer', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
