# Generated by Django 6.0.8 on 2026-09-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_uuid_providerprofile_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=25, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='budget',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Request Budget'),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('document', 'Document'), ('course', 'Course'), ('book', 'Book'), ('journal', 'Journal'), ('article', 'Article'), ('other', 'Other')], default='other', max_length=25, verbose_name='Request Category'),
        ),
    ]
