# Generated by Django 6.0.8 on 2026-09-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_providerprofile_user_alter_request_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Provider country'),
        ),
    ]
