# Generated by Django 6.0.8 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_providerprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, default='en', max_length=10, verbose_name='Preferred language'),
        ),
    ]
