# Generated by Django 6.0.8 on 2026-09-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_move_request_to_requests_app'),
        ('users', '0006_user_preferred_language'),
    ]

    operations = [
    ]
